language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local_dir: docs
  on:
    branch: master
